WITH GROUP_COUNTS AS (
    SELECT USER_ID, COUNT(1) GROUPS_COUNT
    FROM GROUP_USERS
    WHERE SITE_ID = 5
    GROUP BY USER_ID
)
SELECT 
u.ID USER_ID,
su.EMAIL USER_EMAIL,
su.FRIENDLY_NAME,
su.ID SYSTEM_USER_ID,
g.GROUPS_COUNT,
u.CREATED_AT USER_CREATE_DATE,
u.UPDATED_AT USER_UPDATE_DATE,
u.LOGIN_AT USER_LAST_LOGIN
FROM USERS u
JOIN SYSTEM_USERS su ON su.ID = u.SYSTEM_USER_ID
LEFT JOIN GROUP_COUNTS g ON g.USER_ID = u.ID
WHERE u.SITE_ID = 5
AND su.EMAIL IS NOT NULL